repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.321
    hooks:
    - id: pyright
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort